### ISSUE TITLE
Enhancement - HTML Geolocation API

### ISSUE THREAD

**Issue by 0sumrich** [LibrariesHacked/libraries-at-home#10]
I think it would be a good enhancement to add [HTML geolocation](https://www.w3schools.com/html/html5_geolocation.asp) as an enhancement to searching for your nearest library service. 

In the box where it says 
Search by postcode to find library services in your area

You could check whether the user agrees to geolocation when they click in that box.

**Comment by DaveBathnes** [comment]
Yep, this would be good. 

There is a helper function to get the user location which will trigger the permission request https://github.com/LibrariesHacked/libraries-at-home/blob/875fb7244a146b0466d282d3b02b1ea3e7273878/src/helpers/geo.js#L11

I thought one possibility could be:

1. Have another icon button to automatically detect the location
2. Get the location and then use it to get the nearest postcode
3. Add the postcode to the text field and trigger the search

Pretty much the same control is also used on two other sites: Library map https://github.com/LibrariesHacked/librarymap and Mobile libraries https://github.com/LibrariesHacked/mobilelibraries-website so it could also be extended out to those.
